env:
  browser: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
settings:
  react:
    version: detect
rules:
  '@typescript-eslint/explicit-module-boundary-types': off
  'react/prop-types': off